version: "3"
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: ipam_db
    command: "--default-authentication-plugin=mysql_native_password
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: ${PHPIPAM_IMAGE}
    container_name: ipam_web
    restart: unless-stopped
    volumes:
      - ipam_src:/var/www/html
    environment:
      - IPAM_DATABASE_HOST=db
      - IPAM_DATABASE_USER=${MYSQL_USER}
      - IPAM_DATABASE_PASS=${MYSQL_PASSWORD}
      - IPAM_DATABASE_NAME=${MYSQL_DATABASE}
      - IPAM_DATABASE_PORT=3306
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    container_name: ipam_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ipam_src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  ipam_src:
  db_data: